name: Documentation generator

on:
  push:
    branches:
      - main
      - build_docs

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v3
      
      - run: npm clean-install
      - run: npm run build 
      - run: |
          npm i -d @types/node
          npx typedoc

      - name: push documentation files to docs branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          directory: documentation
